# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: "vincewhite19"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v.1.0.7-07da3a1"
  arch: amd64
  os: linux
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
